#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <conio.h>
#include <time.h>
#define MAXN 3000
typedef double Type;
void Display(Type *a, int n);
void BubbleSort(Type *a, int n);
void SelectionSort(Type *a, int n);
void FillRandom(Type *a, int n);
void InsertionSort(Type *a, int n);
void Table(Type *a, int n);
void FillRandom1(Type *a, int n);
void MergeSort(Type *a, int n);
void HeapSort(Type *a, int n);
void CallQuickSort(Type *a, int n);
int SimpleCntInv(Type *a, int n);
void CntInv(Type *a, int n);